# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

env:
  ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}
  MANTLE_NODE: ${{ secrets.MANTLE_NODE }}
  ARBTRIUM_NODE: ${{ secrets.ARBTRIUM_NODE }}
  BLAST_NODE_URL: ${{ secrets.BLAST_NODE_URL }}
  DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
  BATCH_WRITING_SIZE: 500
  CORES: 16
  SLACK_WEBHOOK: "test"
  SUBGRAPH_API_KEY: ${{ secrets.SUBGRAPH_API_KEY }}
  DB_USER: test_user
  DB_PW: test_password
  DB_NAME: test_db
  DB_HOST: localhost
  DB_PORT: 5432

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Type check with mypy
        run: mypy . --explicit-package-bases --pretty --check-untyped-defs